export enum TitleNames {
  id = 'ID',
  createdAt = 'Дата',
  show = 'Показывать',
  deleted = 'Удален',
  active = 'Активный',
  processed = 'Обработан',
  imageId = 'Изображение',
  name = 'Имя',
  description = 'Описание',
  lastName = 'Фамилия',
  mobileNumber = 'Телефон',
  email = 'Email',
	jobTitle = 'Должность',
}
